### PR TITLE
fix: create all directories on setup

### LINKED ISSUE #416: some directories needed by fromager don't exist
Sometimes the user passes path to directories that don't exist, in which case fromager should create them instead of failing

### PR DESCRIPTION
**Pull request by shubhbapna**
fixes #416

### CODE REVIEW

**Review by dhellmann — APPROVED** [review]

**Review by dhellmann — APPROVED** [review]

File: e2e/test_elfdeps.sh [hunk 1]
```diff
@@ -14,7 +14,7 @@ VERSION="2.1.5"
 OS=$(uname)
 if [ "$OS" = "Darwin" ]; then
     NETWORK_ISOLATION=""
-    WHEEL_PLATFORM_TAG="macosx_10_9_universal2"
+    WHEEL_PLATFORM_TAG="macosx_10_13_universal2"
```
Comment (dhellmann) [inline e2e/test_elfdeps.sh:17]: I have a different fix for this in #420 that should be future proof and allow the tests to work on my dev box, too.

**Review by tiran — APPROVED** [review]

File: e2e/test_elfdeps.sh (hunk 1 above)
Comment (tiran) [reply e2e/test_elfdeps.sh]: I have merged main into the branch and resolved the merge conflict.
